# Generated by Django 4.2.8 on 2024-08-18 15:07

import contact.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='Yuji', max_length=255)),
                ('energy_point', models.IntegerField(default=200)),
                ('heart_point', models.IntegerField(default=3)),
                ('villain_strike_left', models.IntegerField(default=3)),
                ('carta_atual', models.CharField(default='', max_length=255)),
                ('atk_atual', models.IntegerField(default=0)),
                ('drawperformed', models.BooleanField(default=False)),
                ('carta_do_vilao', models.CharField(default='', max_length=255)),
                ('atk_do_vilao', models.IntegerField(default=0)),
                ('verification', models.BooleanField(default=False)),
                ('atributo_atual', models.CharField(default='', max_length=255)),
                ('life_round2', models.IntegerField(default=0)),
                ('controle1', models.IntegerField(default=0)),
                ('enemy_life_round2', models.IntegerField(default=4000)),
                ('energy_pointFase1', models.IntegerField(default=0)),
                ('life_round2savepoint', models.IntegerField(default=0)),
                ('rising_energy', models.BooleanField(default=False)),
                ('thounsand_knives', models.BooleanField(default=False)),
                ('millennium_shield', models.BooleanField(default=False)),
                ('angel_wing', models.BooleanField(default=False)),
                ('acceleration', models.BooleanField(default=False)),
                ('calculo_dano_player', models.IntegerField(default=0)),
                ('calculo_dano_inimigo', models.IntegerField(default=0)),
                ('dark_energy', models.IntegerField(default=200)),
                ('dark_energy_shield', models.BooleanField(default=False)),
                ('dark_energy_blast', models.BooleanField(default=False)),
                ('dark_aura', models.BooleanField(default=False)),
                ('defesa_acumulada_inimigo', models.IntegerField(default=0)),
                ('defesa_acumulada', models.IntegerField(default=0)),
                ('turno', models.IntegerField(default=0)),
                ('contagem', models.IntegerField(default=0)),
                ('stand_by', models.BooleanField(default=False)),
                ('feiticos', models.JSONField(blank=True, default=list)),
                ('imagens_feiticos', models.JSONField(blank=True, default=list)),
                ('limite', models.IntegerField(default=3)),
                ('par_linha_coluna', models.JSONField(blank=True, default=list)),
                ('poder_somado', models.IntegerField(default=0)),
                ('contador_batalha3', models.IntegerField(default=0)),
                ('vida_sobrando', models.IntegerField(default=1)),
                ('fim', models.BooleanField(default=False)),
                ('flip', models.BooleanField(default=False)),
                ('comecou', models.BooleanField(default=False)),
                ('superou', models.IntegerField(default=0)),
                ('batalhar', models.BooleanField(default=False)),
                ('monstros_fase3', models.JSONField(blank=True, default=list)),
                ('fase_atual', models.IntegerField(default=1)),
                ('resultado', models.CharField(default='l', max_length=255)),
                ('historiaVariavel', models.IntegerField(default=1)),
                ('historiaVariavel2', models.IntegerField(default=1)),
                ('historiaVariavel3', models.IntegerField(default=1)),
                ('batalha_em_andamento', models.BooleanField(default=False)),
                ('venceu_fase2', models.BooleanField(default=False)),
                ('lista_boss', models.JSONField(blank=True, default=contact.model.default_lista_boss)),
                ('boss_escolhido', models.CharField(default='', max_length=255)),
                ('boss_escolhido_atk', models.IntegerField(default=0)),
                ('lista_imagem', models.JSONField(blank=True, default=contact.model.default_lista_imagem)),
                ('batalha3lista', models.JSONField(blank=True, default=contact.model.default_batalha3lista)),
                ('cardlist', models.JSONField(blank=True, default=contact.model.default_cardlist)),
            ],
        ),
    ]
